
export const metadata = {
  title: 'Gupi Tasks',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html >
      <body>{children}</body>
    </html>
  )
}
